# Generated by Django 5.0.4 on 2024-04-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0020_tbl_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_roomdetails',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
