# Generated by Django 5.0.4 on 2024-04-26 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0007_tbl_aadhar'),
        ('User', '0020_remove_tbl_booking_roomtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_booking',
            name='booking_floor',
        ),
        migrations.CreateModel(
            name='roombooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_floor', models.CharField(max_length=50)),
                ('roomtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_roomtype')),
            ],
        ),
    ]
