# Generated by Django 5.0.4 on 2024-04-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0021_remove_tbl_booking_booking_floor_roombooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='no_of_rooms',
            field=models.IntegerField(default='0'),
        ),
    ]
