# Generated by Django 5.0.4 on 2024-04-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0024_roombooking_tbl_booking_tbl_occupants'),
    ]

    operations = [
        migrations.DeleteModel(
            name='roombooking',
        ),
    ]
