# Generated by Django 5.0.4 on 2024-04-28 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0007_tbl_aadhar'),
        ('User', '0026_roombooking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='roombooking',
            new_name='tbl_roombooking',
        ),
    ]
