# Generated by Django 5.0.4 on 2024-04-28 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0027_rename_roombooking_tbl_roombooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_roombooking',
        ),
    ]
