# Generated by Django 5.0.4 on 2024-04-28 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0007_tbl_aadhar'),
        ('Hotel', '0021_tbl_roomdetails_status'),
        ('User', '0028_delete_tbl_roombooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_roombooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_floor', models.CharField(max_length=50)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_booking')),
                ('room_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.tbl_roomdetails')),
                ('roomtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_roomtype')),
            ],
        ),
    ]
