# Generated by Django 5.0.4 on 2024-04-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0029_tbl_roombooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_roombooking',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
